# Kubernetes deployment configuration for Sprkz PDF Forms
apiVersion: v1
kind: Namespace
metadata:
  name: sprkz-pdf-forms
  labels:
    app.kubernetes.io/name: sprkz-pdf-forms
    app.kubernetes.io/instance: production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sprkz-pdf-forms-config
  namespace: sprkz-pdf-forms
data:
  REACT_APP_VERSION: "1.0.0"
  NODE_ENV: "production"

---
apiVersion: v1
kind: Secret
metadata:
  name: sprkz-pdf-forms-secrets
  namespace: sprkz-pdf-forms
type: Opaque
data:
  # Base64 encoded secrets
  REACT_APP_UNLEASH_CLIENT_KEY: ZGV2ZWxvcG1lbnQta2V5  # development-key
  REACT_APP_SENTRY_DSN: ""  # Add your Sentry DSN here

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprkz-pdf-forms-app
  namespace: sprkz-pdf-forms
  labels:
    app.kubernetes.io/name: sprkz-pdf-forms
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sprkz-pdf-forms
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sprkz-pdf-forms
        app.kubernetes.io/component: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/nginx_status"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: sprkz-pdf-forms
        image: sprkz/pdf-forms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: sprkz-pdf-forms-config
              key: NODE_ENV
        - name: REACT_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: sprkz-pdf-forms-config
              key: REACT_APP_VERSION
        - name: REACT_APP_UNLEASH_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              name: sprkz-pdf-forms-secrets
              key: REACT_APP_UNLEASH_CLIENT_KEY
        - name: REACT_APP_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sprkz-pdf-forms-secrets
              key: REACT_APP_SENTRY_DSN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/detailed
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sprkz-pdf-forms
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: sprkz-pdf-forms-service
  namespace: sprkz-pdf-forms
  labels:
    app.kubernetes.io/name: sprkz-pdf-forms
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: sprkz-pdf-forms
    app.kubernetes.io/component: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprkz-pdf-forms-ingress
  namespace: sprkz-pdf-forms
  labels:
    app.kubernetes.io/name: sprkz-pdf-forms
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options DENY always;
      add_header X-Content-Type-Options nosniff always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
spec:
  tls:
  - hosts:
    - pdf.sprkz.com
    secretName: sprkz-pdf-forms-tls
  rules:
  - host: pdf.sprkz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sprkz-pdf-forms-service
            port:
              number: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sprkz-pdf-forms-pdb
  namespace: sprkz-pdf-forms
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sprkz-pdf-forms
      app.kubernetes.io/component: frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sprkz-pdf-forms-hpa
  namespace: sprkz-pdf-forms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sprkz-pdf-forms-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sprkz-pdf-forms-netpol
  namespace: sprkz-pdf-forms
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sprkz-pdf-forms
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for external APIs (Unleash, Sentry)
  - to: []
    ports:
    - protocol: TCP
      port: 80   # HTTP for external resources

---
# Service Monitor for Prometheus (if using Prometheus Operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sprkz-pdf-forms-metrics
  namespace: sprkz-pdf-forms
  labels:
    app.kubernetes.io/name: sprkz-pdf-forms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sprkz-pdf-forms
      app.kubernetes.io/component: frontend
  endpoints:
  - port: http
    path: /nginx_status
    interval: 30s